In [65]:
import numpy as np

# Создание массивов
a = np.array([[1, 2, 3], [2, 3, 4]])
b0 = np.arange(0, 100, 5).reshape(-1, 5)
b = np.arange(0, 100, 5).reshape(5, -1)
c = np.random.random(10)

# shape и dtype
print(a.shape)
print(a.dtype)

# Индексирование и срезы
print(b[:])
print()
print(b[3][-1]) # тоже самое что и:
print(b[(3, -1)]) # тоже самое что и:
print(b[3, -1])
print()
print(b[[2, 3]])
print(b[[2, 3], 2])
print()
print(b[:, 2]) # третий столбец
print()
print(b[1:4, : : ])

# операции с массивами
print(b/2)
print(b*2) # умножение массива на число
print(b.dot(b0)) # умножение массива на массив
print(b.mean()) # среднее значение массива
print()
print(b.max(axis=0)) # минимум по строкам для каждого столбца
print(b.max(axis=1)) # минимум по столбцам для каждой строки


(2, 3)
int64
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]

75
75
75

[[40 45 50 55]
 [60 65 70 75]]
[50 70]

[10 30 50 70 90]

[[20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]]
[[ 0.   2.5  5.   7.5]
 [10.  12.5 15.  17.5]
 [20.  22.5 25.  27.5]
 [30.  32.5 35.  37.5]
 [40.  42.5 45.  47.5]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]
 [160 170 180 190]]
[[ 1750  1900  2050  2200  2350]
 [ 4750  5300  5850  6400  6950]
 [ 7750  8700  9650 10600 11550]
 [10750 12100 13450 14800 16150]
 [13750 15500 17250 19000 20750]]
47.5

[80 85 90 95]
[15 35 55 75 95]
